//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9168
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.9168.
// 
#pragma warning disable 1591

namespace FD.DataAccessLayer.Zidane {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TasasIGJSoap", Namespace="http://tempuri.org/")]
    public partial class TasasIGJ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSociedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSociedadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSociedadFiltradoTipoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSociedadesFiltradoTipoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TasasIGJ() {
            this.Url = global::Settings.Default.DataAccessLayer_Zidane_TasasIGJ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSociedadCompletedEventHandler GetSociedadCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetSociedadesCompletedEventHandler GetSociedadesCompleted;
        
        /// <remarks/>
        public event GetSociedadFiltradoTipoCompletedEventHandler GetSociedadFiltradoTipoCompleted;
        
        /// <remarks/>
        public event GetSociedadesFiltradoTipoCompletedEventHandler GetSociedadesFiltradoTipoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSociedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSociedad(int NroCorrelativo) {
            object[] results = this.Invoke("GetSociedad", new object[] {
                        NroCorrelativo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSociedadAsync(int NroCorrelativo) {
            this.GetSociedadAsync(NroCorrelativo, null);
        }
        
        /// <remarks/>
        public void GetSociedadAsync(int NroCorrelativo, object userState) {
            if ((this.GetSociedadOperationCompleted == null)) {
                this.GetSociedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSociedadOperationCompleted);
            }
            this.InvokeAsync("GetSociedad", new object[] {
                        NroCorrelativo}, this.GetSociedadOperationCompleted, userState);
        }
        
        private void OnGetSociedadOperationCompleted(object arg) {
            if ((this.GetSociedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSociedadCompleted(this, new GetSociedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSociedades", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSociedades(string RazonSocial) {
            object[] results = this.Invoke("GetSociedades", new object[] {
                        RazonSocial});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSociedadesAsync(string RazonSocial) {
            this.GetSociedadesAsync(RazonSocial, null);
        }
        
        /// <remarks/>
        public void GetSociedadesAsync(string RazonSocial, object userState) {
            if ((this.GetSociedadesOperationCompleted == null)) {
                this.GetSociedadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSociedadesOperationCompleted);
            }
            this.InvokeAsync("GetSociedades", new object[] {
                        RazonSocial}, this.GetSociedadesOperationCompleted, userState);
        }
        
        private void OnGetSociedadesOperationCompleted(object arg) {
            if ((this.GetSociedadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSociedadesCompleted(this, new GetSociedadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSociedadFiltradoTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSociedadFiltradoTipo(int NroCorrelativo, int TipoSoc) {
            object[] results = this.Invoke("GetSociedadFiltradoTipo", new object[] {
                        NroCorrelativo,
                        TipoSoc});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSociedadFiltradoTipoAsync(int NroCorrelativo, int TipoSoc) {
            this.GetSociedadFiltradoTipoAsync(NroCorrelativo, TipoSoc, null);
        }
        
        /// <remarks/>
        public void GetSociedadFiltradoTipoAsync(int NroCorrelativo, int TipoSoc, object userState) {
            if ((this.GetSociedadFiltradoTipoOperationCompleted == null)) {
                this.GetSociedadFiltradoTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSociedadFiltradoTipoOperationCompleted);
            }
            this.InvokeAsync("GetSociedadFiltradoTipo", new object[] {
                        NroCorrelativo,
                        TipoSoc}, this.GetSociedadFiltradoTipoOperationCompleted, userState);
        }
        
        private void OnGetSociedadFiltradoTipoOperationCompleted(object arg) {
            if ((this.GetSociedadFiltradoTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSociedadFiltradoTipoCompleted(this, new GetSociedadFiltradoTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSociedadesFiltradoTipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSociedadesFiltradoTipo(string RazonSocial, int TipoSoc) {
            object[] results = this.Invoke("GetSociedadesFiltradoTipo", new object[] {
                        RazonSocial,
                        TipoSoc});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSociedadesFiltradoTipoAsync(string RazonSocial, int TipoSoc) {
            this.GetSociedadesFiltradoTipoAsync(RazonSocial, TipoSoc, null);
        }
        
        /// <remarks/>
        public void GetSociedadesFiltradoTipoAsync(string RazonSocial, int TipoSoc, object userState) {
            if ((this.GetSociedadesFiltradoTipoOperationCompleted == null)) {
                this.GetSociedadesFiltradoTipoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSociedadesFiltradoTipoOperationCompleted);
            }
            this.InvokeAsync("GetSociedadesFiltradoTipo", new object[] {
                        RazonSocial,
                        TipoSoc}, this.GetSociedadesFiltradoTipoOperationCompleted, userState);
        }
        
        private void OnGetSociedadesFiltradoTipoOperationCompleted(object arg) {
            if ((this.GetSociedadesFiltradoTipoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSociedadesFiltradoTipoCompleted(this, new GetSociedadesFiltradoTipoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetSociedadCompletedEventHandler(object sender, GetSociedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSociedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSociedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetSociedadesCompletedEventHandler(object sender, GetSociedadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSociedadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSociedadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetSociedadFiltradoTipoCompletedEventHandler(object sender, GetSociedadFiltradoTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSociedadFiltradoTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSociedadFiltradoTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetSociedadesFiltradoTipoCompletedEventHandler(object sender, GetSociedadesFiltradoTipoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSociedadesFiltradoTipoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSociedadesFiltradoTipoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591